name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24.3'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          make test

      - name: Build in Docker
        run: |
          make hookbot
